	AnnoJ.config = {

		tracks : [

			{
				id : '1_1',
				name : 'Gene Models (hg19_Gencode_v19.php)',
				type : 'ModelsTrack',
				path : 'Active',
				data : '/aj2/models/hg19_Gencode_v19.php',
				iconCls : 'silk_bricks',
				height : 100,
				scale : 1,
				showControls : 1,
			},
			{
				id : '2_1',
				name : '31-08',
				type : 'MethTrack',
				path : 'Esteller_TransPsych2016',
				data : '/aj2/tracks/ckeown/Esteller_TransPsych2016/Esteller_TransPsych2016/31-08.php',
				iconCls : 'salk_meth',
				height : 40,
				scale : 1,
			},
			{
				id : '2_2',
				name : 'G145',
				type : 'MethTrack',
				path : 'Esteller_TransPsych2016',
				data : '/aj2/tracks/ckeown/Esteller_TransPsych2016/Esteller_TransPsych2016/G145.php',
				iconCls : 'salk_meth',
				height : 40,
				scale : 1,
			},
			{
				id : '2_3',
				name : 'A09',
				type : 'MethTrack',
				path : 'Esteller_TransPsych2016',
				data : '/aj2/tracks/ckeown/Esteller_TransPsych2016/Esteller_TransPsych2016/A09.php',
				iconCls : 'salk_meth',
				height : 40,
				scale : 1,
			},
			{
				id : '2_4',
				name : 'BK1027',
				type : 'MethTrack',
				path : 'Esteller_TransPsych2016',
				data : '/aj2/tracks/ckeown/Esteller_TransPsych2016/Esteller_TransPsych2016/BK1027.php',
				iconCls : 'salk_meth',
				height : 40,
				scale : 1,
			},
			{
				id : '2_5',
				name : 'W145',
				type : 'MethTrack',
				path : 'Esteller_TransPsych2016',
				data : '/aj2/tracks/ckeown/Esteller_TransPsych2016/Esteller_TransPsych2016/W145.php',
				iconCls : 'salk_meth',
				height : 40,
				scale : 1,
			},
		],

		active : [],

		title : 'Esteller_HumanNeurodegenerative',
		genome : '/aj2/genomes/hg19.php',
		bookmarks : '/aj2/includes/common_bookmarks.php',
		analysis : '/aj2/includes/analysis.php',
		location : {
			assembly : '1',
			position : '1',
			bases : 20,
			pixels : 1,
		},
		admin : {
			name : 'Eran Mukamel',
			email : 'emukamel@ucsd.edu',
			notes : '',
		},
		settings : {
			baseline : 0,
			scale : 2,
			multi : 1,
			yaxis : 20,
		},
		citation : '',
		jbuilder : 4.0,
	};
