	AnnoJ.config = {

		tracks : [

			{
				id : '1_1',
				name : 'Gene Models (hg19_Gencode_v19.php)',
				type : 'ModelsTrack',
				path : 'Annotation Models',
				data : '/aj2/models/hg19_Gencode_v19.php',
				iconCls : 'silk_bricks',
				height : 100,
				scale : 1,
				showControls : 1,
			},
			{
				id : '1_2',
				name : 'hg19_CGi',
				type : 'AlignsTrack',
				path : 'Annotation Models',
				data : '/aj2/tracks/emukamel/hg19_test/Annotation_Models/hg19_CGi.php',
				iconCls : 'silk_bricks',
				height : 40,
				scale : 100,
			},
			{
				id : '2_1',
				name : 'mc_cerebellum_SRX838272_1',
				type : 'MethTrack',
				path : 'mC',
				data : '/aj2/tracks/emukamel/hg19_test/mC/mc_cerebellum_SRX838272.php',
				iconCls : 'salk_dna',
				height : 40,
				scale : 1,
			},
			{
				id : '2_2',
				name : 'mc_blood_mononuclear_SRX838242_1',
				type : 'MethTrack',
				path : 'mC',
				data : '/aj2/tracks/emukamel/hg19_test/mC/mc_blood_mononuclear_SRX838242_1.php',
				iconCls : 'salk_dna',
				height : 40,
				scale : 1,
			},
			{
				id : '2_3',
				name : 'mc_broadman_11_SRX838252_1',
				type : 'MethTrack',
				path : 'mC',
				data : '/aj2/tracks/emukamel/hg19_test/mC/mc_broadman_11_SRX838252.php',
				iconCls : 'salk_dna',
				height : 40,
				scale : 1,
			},
			{
				id : '2_4',
				name : 'mc_insular_SRX838269_1',
				type : 'MethTrack',
				path : 'mC',
				data : '/aj2/tracks/emukamel/hg19_test/mC/mc_insular_SRX838269_1.php',
				iconCls : 'salk_dna',
				height : 40,
				scale : 1,
			},
			{
				id : '2_5',
				name : 'mc_hippo_SRX838264_5',
				type : 'MethTrack',
				path : 'mC',
				data : '/aj2/tracks/emukamel/hg19_test/mC/mc_hippo_SRX838264_5.php',
				iconCls : 'salk_dna',
				height : 40,
				scale : 1,
			},
			{
				id : '3_1',
				name : 'DMRs_hg19_hyper_blood_mononuclear_SRX838242_1',
				type : 'IntensityTrack',
				path : 'DMRs',
				data : '/aj2/tracks/emukamel/hg19_test/DMRs/DMRs_hg19_hyper_blood_mononuclear_SRX838242.php',
				iconCls : 'salk_dmr',
				height : 40,
				scale : 1,
			},
			{
				id : '3_2',
				name : 'DMRs_hg19_hyper_blood_mononuclear_SRX838242_1',
				type : 'IntensityTrack',
				path : 'DMRs',
				data : '/aj2/tracks/emukamel/hg19_test/DMRs/DMRs_hg19_hyper_blood_mononuclear_SRX838242_1.php',
				iconCls : 'silk_bricks',
				height : 40,
				scale : 1,
			},
		],

		active : ['1_1', '1_2', '2_1', '3_1', '2_2', '2_4'],

		title : 'hg19_FC_HC_Roadmap',
		genome : '/aj2/genomes/hg19.php',
		bookmarks : '/aj2/includes/common_bookmarks.php',
		analysis : '/aj2/includes/analysis.php',
		location : {
			assembly : '1',
			position : '10000000',
			bases : 200,
			pixels : 1,
		},
		admin : {
			name : 'Eran Mukamel',
			email : 'emukamel@ucsd.edu',
			notes : '',
		},
		settings : {
			baseline : 0,
			scale : 2,
			multi : 1,
			yaxis : 100,
		},
		citation : '',
		jbuilder : 4.0,
	};
